apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-release
  namespace: release
spec:
  replicas: 1 # 启动几个pod
  selector:
    matchLabels:
      app: app-release
  template:
    metadata:
      labels:
        app: app-release #  pod的名称 对应Service 下面app-name
    spec:
      containers:
        - name: app-release
          image: nginx:latest
          imagePullPolicy: "Always"
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: app-release
  namespace: release
spec:
  selector:
    app: app-release # 对应的app-name
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80 # 容器的端口
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: app-release
  namespace: release
spec:
  rules:
    - host: localhost
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: app-release
                port:
                  number: 80
